source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '16.0'

target 'App' do
  use_frameworks!
  pod 'About', :path => '../mod/About'
  pod 'Alert', :path => '../mod/Alert'
  pod 'Const', :path => '../mod/Const'
  pod 'Converter', :path => '../mod/Converter'
  pod 'ConverterUI', :path => '../mod/ConverterUI'
  pod 'Disk', :path => '../mod/Disk'
  pod 'MPAK', :path => '../mod/MPAK'
  pod 'Net', :path => '../mod/Net'
  pod 'SUI', :path => '../mod/SUI'
end
